sample_id:  IcHarAxyr
species_name: Harmonia axyridis
contig_file: /scaff/out.break.salsa/scaffolds_FINAL.fasta
contig_noseq: None
read_file: None

pair_file: /scaff/alignments_sorted.txt
size_file: /scaff/scaffolds_FINAL.fasta.chrom.sizes

assembler: hifiasm
seq_type: scaffolds
collapse_kmers: collapsed

user_group: team301-grp
fastk_path: /software/fastk/
hexamer_path: /software/hexamer
un_count_path: /software/unique-kmers
tetra_count_path: /software/kmer-counter
hextable_path: /software/cds.worm.hex
reduced_plot_path: /software/Select_contigs_reduced_multi.py
hic_link_path: /software/hic_links.py
conda_tf: /software/conda/kmerviz
